import type { StripTheme, StripThemeConfig } from "../types";
import { createDefaultThemeConfig, decorationsFromPreset } from "./defaults";

export const THEME_CATEGORIES = [
  "Classic Photo Booth",
  "Vintage Film",
  "Y2K",
  "Coquette",
  "Cute",
  "Scrapbook",
  "Retro",
  "Disco",
  "Birthday",
  "Party",
  "Love/Friends",
  "Minimal",
  "Seasonal",
  "Holiday",
  "Indian",
  "Custom",
] as const;

export const STRIP_THEMES: StripTheme[] = [
  {
    id: "classic-white",
    name: "Classic White",
    category: "Classic Photo Booth",
    background: { color: "#FFFAF2", pattern: "none" },
    borderStyle: "thin",
    borderColor: "#1A1410",
    photoFrameStyle: "thin",
    photoCornerRadius: 0,
    decorations: [],
    fontStyle: "classic",
    textColor: "#1A1410",
    filterPreset: "none",
    filmGrain: false,
    preview: { swatch: "#FFFAF2", accent: "#1A1410" },
  },
  {
    id: "classic-black",
    name: "Classic Black",
    category: "Classic Photo Booth",
    background: { color: "#14110F", pattern: "none" },
    borderStyle: "thin",
    borderColor: "#F5EDE0",
    photoFrameStyle: "thin",
    photoCornerRadius: 0,
    decorations: [],
    fontStyle: "classic",
    textColor: "#F5EDE0",
    filterPreset: "none",
    filmGrain: false,
    preview: { swatch: "#14110F", accent: "#F5EDE0" },
  },
  {
    id: "vintage-cream",
    name: "Faded Cream",
    category: "Vintage Film",
    background: { color: "#EFE4D0", pattern: "grain", patternOpacity: 0.35 },
    borderStyle: "film",
    borderColor: "#2A241C",
    photoFrameStyle: "vintage",
    photoCornerRadius: 2,
    decorations: [
      { kind: "sprocket", anchor: "margin-left", size: 0.9 },
      { kind: "sprocket", anchor: "margin-right", size: 0.9 },
    ],
    fontStyle: "typewriter",
    textColor: "#3A3228",
    filterPreset: "faded",
    filmGrain: true,
    customTextDefault: "",
    preview: { swatch: "#EFE4D0", accent: "#8B5E3C" },
  },
  {
    id: "vintage-sepia",
    name: "Sepia Reel",
    category: "Vintage Film",
    background: { color: "#E8D5B5", pattern: "paper", patternOpacity: 0.3 },
    borderStyle: "double",
    borderColor: "#5C4030",
    photoFrameStyle: "polaroid",
    photoCornerRadius: 0,
    decorations: [],
    fontStyle: "typewriter",
    textColor: "#4A3426",
    filterPreset: "sepia",
    filmGrain: true,
    preview: { swatch: "#E8D5B5", accent: "#5C4030" },
  },
  {
    id: "y2k-chrome",
    name: "Chrome Dreams",
    category: "Y2K",
    background: {
      color: "#E8F0FF",
      secondaryColor: "#FFD6F0",
      pattern: "stars",
      patternOpacity: 0.4,
    },
    borderStyle: "chrome",
    borderColor: "#9BB4D4",
    photoFrameStyle: "rounded",
    photoCornerRadius: 12,
    decorations: [
      { kind: "star", anchor: "strip-tl", size: 1 },
      { kind: "sparkle", anchor: "strip-tr", size: 0.9 },
      { kind: "star", anchor: "strip-br", size: 0.85 },
    ],
    fontStyle: "display",
    textColor: "#2A1F4A",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "Y2K",
    preview: { swatch: "#E8F0FF", accent: "#FF6BCB" },
  },
  {
    id: "y2k-pink-blue",
    name: "Pink & Blue",
    category: "Y2K",
    background: { color: "#FFB8E0", secondaryColor: "#8EC5FF", pattern: "dots", patternOpacity: 0.25 },
    borderStyle: "thick",
    borderColor: "#5CE1FF",
    photoFrameStyle: "sticker",
    photoCornerRadius: 8,
    decorations: [
      { kind: "sparkle", anchor: "strip-top", size: 1 },
      { kind: "star", anchor: "between-photos", size: 0.7 },
      { kind: "heart", anchor: "footer", size: 0.8, color: "#FF4DA6" },
    ],
    fontStyle: "display",
    textColor: "#1F1A3A",
    filterPreset: "none",
    filmGrain: false,
    preview: { swatch: "#FFB8E0", accent: "#5CE1FF" },
  },
  {
    id: "coquette-bows",
    name: "Ribbon & Bow",
    category: "Coquette",
    background: { color: "#FFE4EF", pattern: "none" },
    borderStyle: "ribbon",
    borderColor: "#E8A0B8",
    photoFrameStyle: "rounded",
    photoCornerRadius: 10,
    decorations: [
      { kind: "bow", anchor: "strip-top", size: 1.1, color: "#E87A9A" },
      { kind: "heart", anchor: "strip-bl", size: 0.75, color: "#F2A0B8" },
      { kind: "heart", anchor: "strip-br", size: 0.7, color: "#F2A0B8" },
    ],
    fontStyle: "handwritten",
    textColor: "#8B3A55",
    filterPreset: "warm",
    filmGrain: false,
    customTextDefault: "xoxo",
    preview: { swatch: "#FFE4EF", accent: "#E87A9A" },
  },
  {
    id: "coquette-lace",
    name: "Soft Lace",
    category: "Coquette",
    background: { color: "#FFF0F5", pattern: "dots", patternOpacity: 0.15 },
    borderStyle: "scalloped",
    borderColor: "#D4A0B0",
    photoFrameStyle: "polaroid",
    photoCornerRadius: 4,
    decorations: [
      { kind: "bow", anchor: "strip-tl", size: 0.85 },
      { kind: "bow", anchor: "strip-tr", size: 0.85 },
    ],
    fontStyle: "handwritten",
    textColor: "#9A4A62",
    filterPreset: "none",
    filmGrain: false,
    preview: { swatch: "#FFF0F5", accent: "#D4A0B0" },
  },
  {
    id: "cute-clouds",
    name: "Cloud Day",
    category: "Cute",
    background: { color: "#E8F6FF", pattern: "none" },
    borderStyle: "thick",
    borderColor: "#A8D4F0",
    photoFrameStyle: "rounded",
    photoCornerRadius: 14,
    decorations: [
      { kind: "cloud", anchor: "strip-tl", size: 1 },
      { kind: "cloud", anchor: "strip-tr", size: 0.9 },
      { kind: "smile", anchor: "footer", size: 0.8 },
    ],
    fontStyle: "handwritten",
    textColor: "#3A5A7A",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "hehe",
    preview: { swatch: "#E8F6FF", accent: "#7EC8E8" },
  },
  {
    id: "cute-cherries",
    name: "Cherry Sweet",
    category: "Cute",
    background: { color: "#FFE8EC", pattern: "dots", patternOpacity: 0.2 },
    borderStyle: "dashed",
    borderColor: "#E85A6A",
    photoFrameStyle: "sticker",
    photoCornerRadius: 10,
    decorations: [
      { kind: "cherry", anchor: "strip-tl", size: 1 },
      { kind: "flower", anchor: "strip-tr", size: 0.9, color: "#FF8FAB" },
      { kind: "cherry", anchor: "strip-br", size: 0.85 },
    ],
    fontStyle: "handwritten",
    textColor: "#A03A48",
    filterPreset: "warm",
    filmGrain: false,
    preview: { swatch: "#FFE8EC", accent: "#E85A6A" },
  },
  {
    id: "scrapbook-tape",
    name: "Washi Tape",
    category: "Scrapbook",
    background: { color: "#F7F0E4", pattern: "paper", patternOpacity: 0.4 },
    borderStyle: "torn",
    borderColor: "#C4B59A",
    photoFrameStyle: "polaroid",
    photoCornerRadius: 0,
    decorations: [
      { kind: "tape", anchor: "strip-top", size: 1.1, color: "#E8C96A" },
      { kind: "doodle", anchor: "margin-right", size: 0.9 },
      { kind: "tape", anchor: "strip-bl", size: 0.9, color: "#A8C8E0" },
    ],
    fontStyle: "handwritten",
    textColor: "#4A4035",
    filterPreset: "faded",
    filmGrain: true,
    preview: { swatch: "#F7F0E4", accent: "#E8C96A" },
  },
  {
    id: "scrapbook-stickers",
    name: "Sticker Page",
    category: "Scrapbook",
    background: { color: "#FFF8EE", pattern: "none" },
    borderStyle: "dashed",
    borderColor: "#B09070",
    photoFrameStyle: "sticker",
    photoCornerRadius: 6,
    decorations: [
      { kind: "star", anchor: "strip-tl", size: 0.85, color: "#F0C040" },
      { kind: "heart", anchor: "strip-tr", size: 0.8, color: "#E07070" },
      { kind: "smile", anchor: "between-photos", size: 0.7 },
      { kind: "doodle", anchor: "footer", size: 0.85 },
    ],
    fontStyle: "handwritten",
    textColor: "#5A4A3A",
    filterPreset: "none",
    filmGrain: false,
    preview: { swatch: "#FFF8EE", accent: "#E07070" },
  },
  {
    id: "retro-checker",
    name: "Checker Pop",
    category: "Retro",
    background: {
      color: "#F4E8C8",
      secondaryColor: "#1A1410",
      pattern: "checker",
      patternOpacity: 0.2,
    },
    borderStyle: "thick",
    borderColor: "#E85D04",
    photoFrameStyle: "thin",
    photoCornerRadius: 0,
    decorations: [
      { kind: "checker", anchor: "strip-top", size: 0.8 },
      { kind: "wave", anchor: "footer", size: 1 },
    ],
    fontStyle: "display",
    textColor: "#1A1410",
    filterPreset: "warm",
    filmGrain: false,
    customTextDefault: "GROOVY",
    preview: { swatch: "#F4E8C8", accent: "#E85D04" },
  },
  {
    id: "retro-waves",
    name: "70s Waves",
    category: "Retro",
    background: {
      color: "#F6D6A8",
      secondaryColor: "#C45C26",
      pattern: "waves",
      patternOpacity: 0.35,
    },
    borderStyle: "double",
    borderColor: "#8B3A1A",
    photoFrameStyle: "rounded",
    photoCornerRadius: 8,
    decorations: [{ kind: "wave", anchor: "between-photos", size: 0.9 }],
    fontStyle: "display",
    textColor: "#5A2810",
    filterPreset: "sepia",
    filmGrain: false,
    preview: { swatch: "#F6D6A8", accent: "#C45C26" },
  },
  {
    id: "disco-glitter",
    name: "Disco Night",
    category: "Disco",
    background: {
      color: "#1A1030",
      secondaryColor: "#FFD700",
      pattern: "glitter",
      patternOpacity: 0.45,
    },
    borderStyle: "chrome",
    borderColor: "#D4AF37",
    photoFrameStyle: "thin",
    photoCornerRadius: 4,
    decorations: [
      { kind: "disco", anchor: "strip-top", size: 1.15 },
      { kind: "star", anchor: "strip-bl", size: 0.9, color: "#FFD700" },
      { kind: "sparkle", anchor: "strip-br", size: 0.95, color: "#E8E0FF" },
    ],
    fontStyle: "display",
    textColor: "#FFE8A0",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "DISCO",
    preview: { swatch: "#1A1030", accent: "#FFD700" },
  },
  {
    id: "disco-stars",
    name: "Studio 54",
    category: "Disco",
    background: { color: "#2A1040", pattern: "stars", patternOpacity: 0.5 },
    borderStyle: "thick",
    borderColor: "#E040A0",
    photoFrameStyle: "rounded",
    photoCornerRadius: 10,
    decorations: [
      { kind: "star", anchor: "strip-tl", size: 1, color: "#FFD700" },
      { kind: "star", anchor: "strip-tr", size: 0.85, color: "#FF70C0" },
      { kind: "disco", anchor: "footer", size: 0.9 },
    ],
    fontStyle: "display",
    textColor: "#FFD0F0",
    filterPreset: "none",
    filmGrain: false,
    preview: { swatch: "#2A1040", accent: "#E040A0" },
  },
  {
    id: "birthday-cake",
    name: "Birthday Cake",
    category: "Birthday",
    background: { color: "#FFF5E8", pattern: "dots", patternOpacity: 0.25 },
    borderStyle: "scalloped",
    borderColor: "#FF8A65",
    photoFrameStyle: "rounded",
    photoCornerRadius: 10,
    decorations: [
      { kind: "cake", anchor: "strip-top", size: 1.1 },
      { kind: "balloon", anchor: "strip-tl", size: 0.9, color: "#FF6B8A" },
      { kind: "confetti", anchor: "between-photos", size: 0.85 },
      { kind: "balloon", anchor: "strip-tr", size: 0.85, color: "#6BCBFF" },
    ],
    fontStyle: "handwritten",
    textColor: "#8A3A2A",
    filterPreset: "warm",
    filmGrain: false,
    customTextDefault: "Happy Birthday!",
    preview: { swatch: "#FFF5E8", accent: "#FF8A65" },
  },
  {
    id: "party-confetti",
    name: "Party Pop",
    category: "Party",
    background: { color: "#FFF8E7", pattern: "none" },
    borderStyle: "thick",
    borderColor: "#FF5C8A",
    photoFrameStyle: "sticker",
    photoCornerRadius: 8,
    decorations: [
      { kind: "confetti", anchor: "strip-top", size: 1 },
      { kind: "star", anchor: "strip-bl", size: 0.8, color: "#FFD93D" },
      { kind: "balloon", anchor: "strip-br", size: 0.9, color: "#6BCB77" },
    ],
    fontStyle: "display",
    textColor: "#2A1A30",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "LET'S PARTY",
    preview: { swatch: "#FFF8E7", accent: "#FF5C8A" },
  },
  {
    id: "love-hearts",
    name: "Heart Eyes",
    category: "Love/Friends",
    background: { color: "#FFE8F0", pattern: "none" },
    borderStyle: "scalloped",
    borderColor: "#E85A7A",
    photoFrameStyle: "rounded",
    photoCornerRadius: 12,
    decorations: [
      { kind: "heart", anchor: "strip-tl", size: 1, color: "#E85A7A" },
      { kind: "hearts-cluster", anchor: "strip-tr", size: 1 },
      { kind: "heart", anchor: "footer", size: 0.85, color: "#FF8AAB" },
    ],
    fontStyle: "handwritten",
    textColor: "#8A2848",
    filterPreset: "warm",
    filmGrain: false,
    customTextDefault: "love u",
    preview: { swatch: "#FFE8F0", accent: "#E85A7A" },
  },
  {
    id: "friends-besties",
    name: "Besties",
    category: "Love/Friends",
    background: { color: "#FFF0E8", pattern: "dots", patternOpacity: 0.2 },
    borderStyle: "dashed",
    borderColor: "#E8A070",
    photoFrameStyle: "polaroid",
    photoCornerRadius: 4,
    decorations: [
      { kind: "besties", anchor: "strip-top", size: 1.1 },
      { kind: "heart", anchor: "between-photos", size: 0.75, color: "#FF7A9A" },
      { kind: "star", anchor: "footer", size: 0.8, color: "#FFD06A" },
    ],
    fontStyle: "handwritten",
    textColor: "#6A3A2A",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "Besties",
    preview: { swatch: "#FFF0E8", accent: "#E8A070" },
  },
  {
    id: "minimal-clean",
    name: "Clean Line",
    category: "Minimal",
    background: { color: "#FAFAF8", pattern: "none" },
    borderStyle: "thin",
    borderColor: "#2A2A28",
    photoFrameStyle: "none",
    photoCornerRadius: 0,
    decorations: [],
    fontStyle: "modern",
    textColor: "#2A2A28",
    filterPreset: "none",
    filmGrain: false,
    preview: { swatch: "#FAFAF8", accent: "#2A2A28" },
  },
  {
    id: "minimal-soft",
    name: "Soft Edge",
    category: "Minimal",
    background: { color: "#F2F0EB", pattern: "none" },
    borderStyle: "none",
    borderColor: "#C8C4BC",
    photoFrameStyle: "rounded",
    photoCornerRadius: 6,
    decorations: [],
    fontStyle: "modern",
    textColor: "#3A3834",
    filterPreset: "faded",
    filmGrain: false,
    preview: { swatch: "#F2F0EB", accent: "#8A8680" },
  },
  {
    id: "seasonal-summer",
    name: "Summer Sun",
    category: "Seasonal",
    background: { color: "#FFF6D8", pattern: "none" },
    borderStyle: "thick",
    borderColor: "#F0A020",
    photoFrameStyle: "rounded",
    photoCornerRadius: 10,
    decorations: [
      { kind: "flower", anchor: "strip-tl", size: 1, color: "#FF8A3A" },
      { kind: "flower", anchor: "strip-br", size: 0.9, color: "#FFD06A" },
    ],
    fontStyle: "handwritten",
    textColor: "#7A4A10",
    filterPreset: "warm",
    filmGrain: false,
    customTextDefault: "summer",
    preview: { swatch: "#FFF6D8", accent: "#F0A020" },
  },
  {
    id: "seasonal-winter",
    name: "Winter Frost",
    category: "Seasonal",
    background: { color: "#EEF4FA", pattern: "dots", patternOpacity: 0.2 },
    borderStyle: "thin",
    borderColor: "#7A9AB8",
    photoFrameStyle: "rounded",
    photoCornerRadius: 8,
    decorations: [
      { kind: "snowflake", anchor: "strip-tl", size: 1 },
      { kind: "snowflake", anchor: "strip-tr", size: 0.85 },
      { kind: "snowflake", anchor: "footer", size: 0.8 },
    ],
    fontStyle: "modern",
    textColor: "#3A4A5A",
    filterPreset: "none",
    filmGrain: false,
    preview: { swatch: "#EEF4FA", accent: "#7A9AB8" },
  },
  {
    id: "seasonal-fall",
    name: "Autumn Leaves",
    category: "Seasonal",
    background: { color: "#F5E6D0", pattern: "paper", patternOpacity: 0.25 },
    borderStyle: "double",
    borderColor: "#B85A2A",
    photoFrameStyle: "vintage",
    photoCornerRadius: 2,
    decorations: [
      { kind: "leaf", anchor: "strip-tl", size: 1, color: "#D4783A" },
      { kind: "leaf", anchor: "strip-br", size: 0.9, color: "#C45C26" },
    ],
    fontStyle: "typewriter",
    textColor: "#5A3018",
    filterPreset: "sepia",
    filmGrain: true,
    preview: { swatch: "#F5E6D0", accent: "#B85A2A" },
  },
  {
    id: "seasonal-spring",
    name: "Spring Bloom",
    category: "Seasonal",
    background: { color: "#F0FAF0", pattern: "none" },
    borderStyle: "scalloped",
    borderColor: "#8FBF8F",
    photoFrameStyle: "rounded",
    photoCornerRadius: 12,
    decorations: [
      { kind: "flower", anchor: "strip-tl", size: 1, color: "#F0A0C0" },
      { kind: "flower", anchor: "strip-tr", size: 0.9, color: "#A0D0F0" },
      { kind: "flower", anchor: "footer", size: 0.8, color: "#C0E070" },
    ],
    fontStyle: "handwritten",
    textColor: "#3A6A4A",
    filterPreset: "none",
    filmGrain: false,
    preview: { swatch: "#F0FAF0", accent: "#8FBF8F" },
  },
  {
    id: "holiday-halloween",
    name: "Halloween",
    category: "Holiday",
    background: { color: "#1A1420", pattern: "stars", patternOpacity: 0.3 },
    borderStyle: "thick",
    borderColor: "#FF7A1A",
    photoFrameStyle: "thin",
    photoCornerRadius: 4,
    decorations: [
      { kind: "pumpkin", anchor: "strip-top", size: 1.1 },
      { kind: "star", anchor: "strip-bl", size: 0.85, color: "#FFD06A" },
      { kind: "sparkle", anchor: "strip-br", size: 0.8, color: "#C080FF" },
    ],
    fontStyle: "display",
    textColor: "#FFB060",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "BOO!",
    preview: { swatch: "#1A1420", accent: "#FF7A1A" },
  },
  {
    id: "holiday-christmas",
    name: "Christmas",
    category: "Holiday",
    background: { color: "#F8F4EC", pattern: "none" },
    borderStyle: "double",
    borderColor: "#C41E3A",
    photoFrameStyle: "polaroid",
    photoCornerRadius: 2,
    decorations: [
      { kind: "tree", anchor: "strip-top", size: 1.1 },
      { kind: "star", anchor: "strip-tl", size: 0.85, color: "#FFD700" },
      { kind: "snowflake", anchor: "strip-tr", size: 0.8 },
    ],
    fontStyle: "classic",
    textColor: "#1A4028",
    filterPreset: "warm",
    filmGrain: false,
    customTextDefault: "Merry Christmas",
    preview: { swatch: "#F8F4EC", accent: "#C41E3A" },
  },
  {
    id: "holiday-valentines",
    name: "Valentine's",
    category: "Holiday",
    background: { color: "#FFF0F4", pattern: "dots", patternOpacity: 0.2 },
    borderStyle: "scalloped",
    borderColor: "#E02050",
    photoFrameStyle: "rounded",
    photoCornerRadius: 12,
    decorations: [
      { kind: "hearts-cluster", anchor: "strip-top", size: 1.15 },
      { kind: "heart", anchor: "strip-bl", size: 0.9, color: "#E02050" },
      { kind: "bow", anchor: "strip-br", size: 0.85, color: "#FF6A9A" },
    ],
    fontStyle: "handwritten",
    textColor: "#8A1030",
    filterPreset: "warm",
    filmGrain: false,
    customTextDefault: "Be Mine",
    preview: { swatch: "#FFF0F4", accent: "#E02050" },
  },
  {
    id: "holiday-newyear",
    name: "New Year",
    category: "Holiday",
    background: {
      color: "#101820",
      secondaryColor: "#FFD700",
      pattern: "glitter",
      patternOpacity: 0.4,
    },
    borderStyle: "chrome",
    borderColor: "#D4AF37",
    photoFrameStyle: "thin",
    photoCornerRadius: 0,
    decorations: [
      { kind: "sparkle", anchor: "strip-tl", size: 1, color: "#FFD700" },
      { kind: "star", anchor: "strip-tr", size: 1, color: "#E8E0FF" },
      { kind: "confetti", anchor: "footer", size: 1 },
    ],
    fontStyle: "display",
    textColor: "#FFE8A0",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "Happy New Year",
    preview: { swatch: "#101820", accent: "#FFD700" },
  },
  // —— Extra Classic ——
  {
    id: "classic-red",
    name: "Curtain Red",
    category: "Classic Photo Booth",
    background: { color: "#FFF8F4", pattern: "none" },
    borderStyle: "thick",
    borderColor: "#D4213A",
    photoFrameStyle: "thin",
    photoCornerRadius: 0,
    decorations: [],
    fontStyle: "classic",
    textColor: "#8F1428",
    filterPreset: "none",
    filmGrain: false,
    preview: { swatch: "#FFF8F4", accent: "#D4213A" },
  },
  {
    id: "classic-chrome",
    name: "Mall Chrome",
    category: "Classic Photo Booth",
    background: { color: "#F2F4F8", pattern: "none" },
    borderStyle: "chrome",
    borderColor: "#8E99A8",
    photoFrameStyle: "thin",
    photoCornerRadius: 0,
    decorations: [
      { kind: "sparkle", anchor: "strip-tl", size: 0.7, color: "#C5CCD6" },
      { kind: "sparkle", anchor: "strip-br", size: 0.65, color: "#A8B0BC" },
    ],
    fontStyle: "modern",
    textColor: "#2A3038",
    filterPreset: "none",
    filmGrain: false,
    preview: { swatch: "#F2F4F8", accent: "#8E99A8" },
  },

  // —— Extra Vintage ——
  {
    id: "vintage-polaroid",
    name: "Polaroid Stack",
    category: "Vintage Film",
    background: { color: "#F4EDE2", pattern: "paper", patternOpacity: 0.25 },
    borderStyle: "thin",
    borderColor: "#C8B8A0",
    photoFrameStyle: "polaroid",
    photoCornerRadius: 0,
    decorations: [
      { kind: "tape", anchor: "strip-top", size: 1, color: "#E8D090" },
      { kind: "doodle", anchor: "footer", size: 0.8, color: "#6A5A48" },
    ],
    fontStyle: "handwritten",
    textColor: "#4A3A2A",
    filterPreset: "warm",
    filmGrain: true,
    customTextDefault: "memories",
    preview: { swatch: "#F4EDE2", accent: "#C8B8A0" },
  },
  {
    id: "vintage-noir",
    name: "Film Noir",
    category: "Vintage Film",
    background: { color: "#1A1816", pattern: "grain", patternOpacity: 0.4 },
    borderStyle: "film",
    borderColor: "#E8E0D4",
    photoFrameStyle: "thin",
    photoCornerRadius: 0,
    decorations: [
      { kind: "sprocket", anchor: "margin-left", size: 0.85 },
      { kind: "sprocket", anchor: "margin-right", size: 0.85 },
    ],
    fontStyle: "typewriter",
    textColor: "#E8E0D4",
    filterPreset: "bw",
    filmGrain: true,
    customTextDefault: "NOIR",
    preview: { swatch: "#1A1816", accent: "#E8E0D4" },
  },

  // —— Extra Y2K ——
  {
    id: "y2k-butterfly",
    name: "Butterfly.com",
    category: "Y2K",
    background: {
      color: "#F0E8FF",
      secondaryColor: "#FFD0F0",
      pattern: "stars",
      patternOpacity: 0.35,
    },
    borderStyle: "chrome",
    borderColor: "#C8A0E8",
    photoFrameStyle: "rounded",
    photoCornerRadius: 14,
    decorations: [
      { kind: "butterfly", anchor: "strip-tl", size: 1, color: "#C080FF" },
      { kind: "butterfly", anchor: "strip-br", size: 0.85, color: "#FF80C0" },
      { kind: "sparkle", anchor: "strip-tr", size: 0.9, color: "#80D0FF" },
    ],
    fontStyle: "display",
    textColor: "#4A2A6A",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "www.",
    preview: { swatch: "#F0E8FF", accent: "#C080FF" },
  },
  {
    id: "y2k-lightning",
    name: "Electric Pop",
    category: "Y2K",
    background: { color: "#0E1028", pattern: "stars", patternOpacity: 0.45 },
    borderStyle: "thick",
    borderColor: "#5CE1FF",
    photoFrameStyle: "sticker",
    photoCornerRadius: 8,
    decorations: [
      { kind: "lightning", anchor: "strip-tl", size: 1.1, color: "#FFE84A" },
      { kind: "star", anchor: "strip-tr", size: 0.9, color: "#FF6BCB" },
      { kind: "lightning", anchor: "footer", size: 0.85, color: "#5CE1FF" },
    ],
    fontStyle: "display",
    textColor: "#E8F0FF",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "ZAP!",
    preview: { swatch: "#0E1028", accent: "#5CE1FF" },
  },

  // —— Extra Coquette ——
  {
    id: "coquette-pearl",
    name: "Pearl Ribbon",
    category: "Coquette",
    background: { color: "#FFF6FA", pattern: "dots", patternOpacity: 0.12 },
    borderStyle: "scalloped",
    borderColor: "#E8C0D0",
    photoFrameStyle: "rounded",
    photoCornerRadius: 12,
    decorations: [
      { kind: "bow", anchor: "strip-top", size: 1.05, color: "#F0A0C0" },
      { kind: "sparkle", anchor: "strip-bl", size: 0.7, color: "#E8D0E0" },
      { kind: "sparkle", anchor: "strip-br", size: 0.7, color: "#E8D0E0" },
    ],
    fontStyle: "handwritten",
    textColor: "#9A5A72",
    filterPreset: "warm",
    filmGrain: false,
    customTextDefault: "darling",
    preview: { swatch: "#FFF6FA", accent: "#F0A0C0" },
  },
  {
    id: "coquette-cherry",
    name: "Cherry Kiss",
    category: "Coquette",
    background: { color: "#FFE8F0", pattern: "none" },
    borderStyle: "ribbon",
    borderColor: "#E05070",
    photoFrameStyle: "polaroid",
    photoCornerRadius: 4,
    decorations: [
      { kind: "cherry", anchor: "strip-tl", size: 1 },
      { kind: "bow", anchor: "strip-tr", size: 0.9, color: "#E05070" },
      { kind: "heart", anchor: "footer", size: 0.75, color: "#FF8AAB" },
    ],
    fontStyle: "handwritten",
    textColor: "#8A2848",
    filterPreset: "warm",
    filmGrain: false,
    customTextDefault: "kiss kiss",
    preview: { swatch: "#FFE8F0", accent: "#E05070" },
  },

  // —— Extra Cute ——
  {
    id: "cute-icecream",
    name: "Ice Cream Day",
    category: "Cute",
    background: { color: "#FFF0F8", pattern: "dots", patternOpacity: 0.22 },
    borderStyle: "scalloped",
    borderColor: "#FF9AC8",
    photoFrameStyle: "rounded",
    photoCornerRadius: 14,
    decorations: [
      { kind: "icecream", anchor: "strip-top", size: 1.1 },
      { kind: "cloud", anchor: "strip-bl", size: 0.85 },
      { kind: "smile", anchor: "strip-br", size: 0.8 },
    ],
    fontStyle: "handwritten",
    textColor: "#A04868",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "sweet!",
    preview: { swatch: "#FFF0F8", accent: "#FF9AC8" },
  },
  {
    id: "cute-starsmile",
    name: "Star Smile",
    category: "Cute",
    background: { color: "#FFFBE8", pattern: "stars", patternOpacity: 0.25 },
    borderStyle: "dashed",
    borderColor: "#F0C040",
    photoFrameStyle: "sticker",
    photoCornerRadius: 12,
    decorations: [
      { kind: "star", anchor: "strip-tl", size: 1, color: "#FFD06A" },
      { kind: "smile", anchor: "strip-tr", size: 0.95 },
      { kind: "star", anchor: "footer", size: 0.8, color: "#FFB040" },
    ],
    fontStyle: "handwritten",
    textColor: "#8A6020",
    filterPreset: "warm",
    filmGrain: false,
    customTextDefault: "yay!",
    preview: { swatch: "#FFFBE8", accent: "#F0C040" },
  },

  // —— Extra Scrapbook ——
  {
    id: "scrapbook-memory",
    name: "Memory Lane",
    category: "Scrapbook",
    background: { color: "#F8F0E4", pattern: "paper", patternOpacity: 0.35 },
    borderStyle: "torn",
    borderColor: "#C4A882",
    photoFrameStyle: "polaroid",
    photoCornerRadius: 0,
    decorations: [
      { kind: "tape", anchor: "strip-tl", size: 0.95, color: "#E8A0B0" },
      { kind: "tape", anchor: "strip-tr", size: 0.9, color: "#A0C8E0" },
      { kind: "doodle", anchor: "between-photos", size: 0.85, color: "#8A7060" },
      { kind: "flower", anchor: "footer", size: 0.75, color: "#E89090" },
    ],
    fontStyle: "handwritten",
    textColor: "#5A4030",
    filterPreset: "faded",
    filmGrain: true,
    customTextDefault: "this day",
    preview: { swatch: "#F8F0E4", accent: "#E8A0B0" },
  },
  {
    id: "scrapbook-kraft",
    name: "Kraft Paper",
    category: "Scrapbook",
    background: { color: "#E8D8C0", pattern: "paper", patternOpacity: 0.4 },
    borderStyle: "dashed",
    borderColor: "#8A6A48",
    photoFrameStyle: "sticker",
    photoCornerRadius: 4,
    decorations: [
      { kind: "doodle", anchor: "strip-top", size: 1, color: "#6A4A30" },
      { kind: "star", anchor: "strip-bl", size: 0.8, color: "#C09050" },
      { kind: "heart", anchor: "strip-br", size: 0.75, color: "#C06060" },
    ],
    fontStyle: "typewriter",
    textColor: "#4A3020",
    filterPreset: "sepia",
    filmGrain: false,
    preview: { swatch: "#E8D8C0", accent: "#8A6A48" },
  },

  // —— Extra Retro ——
  {
    id: "retro-sunset",
    name: "Sunset Strip",
    category: "Retro",
    background: {
      color: "#FFB070",
      secondaryColor: "#E04060",
      pattern: "waves",
      patternOpacity: 0.3,
    },
    borderStyle: "thick",
    borderColor: "#6A2040",
    photoFrameStyle: "rounded",
    photoCornerRadius: 6,
    decorations: [
      { kind: "wave", anchor: "strip-top", size: 1, color: "#FFD090" },
      { kind: "star", anchor: "footer", size: 1.05, color: "#FFE080" },
    ],
    fontStyle: "display",
    textColor: "#4A1830",
    filterPreset: "warm",
    filmGrain: false,
    customTextDefault: "SUNSET",
    preview: { swatch: "#FFB070", accent: "#E04060" },
  },
  {
    id: "retro-arcade",
    name: "Arcade Night",
    category: "Retro",
    background: { color: "#1A1030", pattern: "checker", patternOpacity: 0.15, secondaryColor: "#FF40A0" },
    borderStyle: "chrome",
    borderColor: "#40E0FF",
    photoFrameStyle: "thin",
    photoCornerRadius: 0,
    decorations: [
      { kind: "lightning", anchor: "strip-tl", size: 1, color: "#FFE040" },
      { kind: "star", anchor: "strip-tr", size: 0.9, color: "#FF40A0" },
      { kind: "music", anchor: "footer", size: 0.9, color: "#40E0FF" },
    ],
    fontStyle: "display",
    textColor: "#E8F0FF",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "INSERT COIN",
    preview: { swatch: "#1A1030", accent: "#40E0FF" },
  },

  // —— Extra Disco ——
  {
    id: "disco-gold",
    name: "Gold Rush",
    category: "Disco",
    background: {
      color: "#2A2010",
      secondaryColor: "#FFD700",
      pattern: "glitter",
      patternOpacity: 0.5,
    },
    borderStyle: "chrome",
    borderColor: "#FFD700",
    photoFrameStyle: "rounded",
    photoCornerRadius: 8,
    decorations: [
      { kind: "disco", anchor: "strip-top", size: 1.2 },
      { kind: "sparkle", anchor: "strip-bl", size: 0.95, color: "#FFE8A0" },
      { kind: "sparkle", anchor: "strip-br", size: 0.9, color: "#FFD700" },
    ],
    fontStyle: "display",
    textColor: "#FFE8A0",
    filterPreset: "warm",
    filmGrain: false,
    customTextDefault: "GOLD",
    preview: { swatch: "#2A2010", accent: "#FFD700" },
  },
  {
    id: "disco-neon",
    name: "Neon Floor",
    category: "Disco",
    background: { color: "#100820", pattern: "stars", patternOpacity: 0.4 },
    borderStyle: "thick",
    borderColor: "#FF20A0",
    photoFrameStyle: "thin",
    photoCornerRadius: 2,
    decorations: [
      { kind: "music", anchor: "strip-tl", size: 1, color: "#40FFE0" },
      { kind: "disco", anchor: "strip-tr", size: 1 },
      { kind: "star", anchor: "footer", size: 0.9, color: "#FF20A0" },
    ],
    fontStyle: "display",
    textColor: "#FFB0E0",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "DANCE",
    preview: { swatch: "#100820", accent: "#FF20A0" },
  },

  // —— Extra Birthday / Party ——
  {
    id: "birthday-pastel",
    name: "Pastel Party",
    category: "Birthday",
    background: { color: "#F8F0FF", pattern: "dots", patternOpacity: 0.25 },
    borderStyle: "scalloped",
    borderColor: "#C8A0E8",
    photoFrameStyle: "rounded",
    photoCornerRadius: 12,
    decorations: [
      { kind: "balloon", anchor: "strip-tl", size: 0.95, color: "#FF9AD0" },
      { kind: "balloon", anchor: "strip-tr", size: 0.9, color: "#9AD0FF" },
      { kind: "cake", anchor: "footer", size: 1 },
      { kind: "confetti", anchor: "between-photos", size: 0.8 },
    ],
    fontStyle: "handwritten",
    textColor: "#6A4A8A",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "make a wish",
    preview: { swatch: "#F8F0FF", accent: "#C8A0E8" },
  },
  {
    id: "party-neon",
    name: "Neon Bash",
    category: "Party",
    background: { color: "#12101C", pattern: "glitter", patternOpacity: 0.35, secondaryColor: "#FF40C0" },
    borderStyle: "chrome",
    borderColor: "#40FFE0",
    photoFrameStyle: "sticker",
    photoCornerRadius: 10,
    decorations: [
      { kind: "confetti", anchor: "strip-top", size: 1.1 },
      { kind: "lightning", anchor: "strip-bl", size: 0.9, color: "#FFE040" },
      { kind: "star", anchor: "strip-br", size: 0.9, color: "#FF40C0" },
    ],
    fontStyle: "display",
    textColor: "#E0FFF8",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "PARTY TIME",
    preview: { swatch: "#12101C", accent: "#40FFE0" },
  },
  {
    id: "party-carnival",
    name: "Carnival",
    category: "Party",
    background: { color: "#FFF5E8", pattern: "checker", patternOpacity: 0.12, secondaryColor: "#E04040" },
    borderStyle: "thick",
    borderColor: "#E04040",
    photoFrameStyle: "rounded",
    photoCornerRadius: 8,
    decorations: [
      { kind: "star", anchor: "strip-tl", size: 1, color: "#FFD040" },
      { kind: "balloon", anchor: "strip-tr", size: 0.95, color: "#4080E0" },
      { kind: "confetti", anchor: "footer", size: 1 },
    ],
    fontStyle: "display",
    textColor: "#6A2020",
    filterPreset: "warm",
    filmGrain: false,
    customTextDefault: "FUN!",
    preview: { swatch: "#FFF5E8", accent: "#E04040" },
  },

  // —— Extra Love/Friends ——
  {
    id: "love-moon",
    name: "Moonlit Love",
    category: "Love/Friends",
    background: { color: "#1A1428", pattern: "stars", patternOpacity: 0.45 },
    borderStyle: "thin",
    borderColor: "#E8C8FF",
    photoFrameStyle: "rounded",
    photoCornerRadius: 10,
    decorations: [
      { kind: "moon", anchor: "strip-top", size: 1.15, color: "#F0E0A0" },
      { kind: "heart", anchor: "strip-bl", size: 0.85, color: "#FF80B0" },
      { kind: "star", anchor: "strip-br", size: 0.8, color: "#E0D0FF" },
    ],
    fontStyle: "handwritten",
    textColor: "#F0E0FF",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "to the moon",
    preview: { swatch: "#1A1428", accent: "#E8C8FF" },
  },
  {
    id: "friends-squad",
    name: "Squad Goals",
    category: "Love/Friends",
    background: { color: "#E8F8FF", pattern: "dots", patternOpacity: 0.2 },
    borderStyle: "dashed",
    borderColor: "#40A0D0",
    photoFrameStyle: "sticker",
    photoCornerRadius: 10,
    decorations: [
      { kind: "besties", anchor: "strip-top", size: 1.1, color: "#2080B0" },
      { kind: "star", anchor: "strip-bl", size: 0.8, color: "#FFD060" },
      { kind: "heart", anchor: "strip-br", size: 0.8, color: "#FF7090" },
    ],
    fontStyle: "handwritten",
    textColor: "#205070",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "squad",
    preview: { swatch: "#E8F8FF", accent: "#40A0D0" },
  },
  {
    id: "love-crown",
    name: "Main Character",
    category: "Love/Friends",
    background: { color: "#FFF8E8", pattern: "none" },
    borderStyle: "double",
    borderColor: "#E2B84A",
    photoFrameStyle: "polaroid",
    photoCornerRadius: 2,
    decorations: [
      { kind: "crown", anchor: "strip-top", size: 1.15, color: "#E2B84A" },
      { kind: "sparkle", anchor: "strip-bl", size: 0.85, color: "#F0D070" },
      { kind: "sparkle", anchor: "strip-br", size: 0.8, color: "#F0D070" },
    ],
    fontStyle: "display",
    textColor: "#6A4A10",
    filterPreset: "warm",
    filmGrain: false,
    customTextDefault: "iconic",
    preview: { swatch: "#FFF8E8", accent: "#E2B84A" },
  },

  // —— Extra Minimal ——
  {
    id: "minimal-navy",
    name: "Navy Line",
    category: "Minimal",
    background: { color: "#F4F6FA", pattern: "none" },
    borderStyle: "thin",
    borderColor: "#1A2A40",
    photoFrameStyle: "none",
    photoCornerRadius: 0,
    decorations: [],
    fontStyle: "modern",
    textColor: "#1A2A40",
    filterPreset: "none",
    filmGrain: false,
    preview: { swatch: "#F4F6FA", accent: "#1A2A40" },
  },
  {
    id: "minimal-blush",
    name: "Blush Quiet",
    category: "Minimal",
    background: { color: "#FBF4F2", pattern: "none" },
    borderStyle: "none",
    borderColor: "#E0C8C0",
    photoFrameStyle: "rounded",
    photoCornerRadius: 8,
    decorations: [],
    fontStyle: "modern",
    textColor: "#6A4A48",
    filterPreset: "faded",
    filmGrain: false,
    preview: { swatch: "#FBF4F2", accent: "#E0C8C0" },
  },

  // —— Extra Seasonal ——
  {
    id: "seasonal-beach",
    name: "Beach Day",
    category: "Seasonal",
    background: { color: "#E8F6FF", pattern: "waves", patternOpacity: 0.25, secondaryColor: "#40A0D0" },
    borderStyle: "thick",
    borderColor: "#40A0D0",
    photoFrameStyle: "rounded",
    photoCornerRadius: 12,
    decorations: [
      { kind: "wave", anchor: "strip-top", size: 1, color: "#60B8E0" },
      { kind: "cloud", anchor: "strip-tr", size: 0.85 },
      { kind: "star", anchor: "footer", size: 0.8, color: "#FFD060" },
    ],
    fontStyle: "handwritten",
    textColor: "#205070",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "beach vibes",
    preview: { swatch: "#E8F6FF", accent: "#40A0D0" },
  },
  {
    id: "seasonal-cozy",
    name: "Cozy Night",
    category: "Seasonal",
    background: { color: "#2A1C18", pattern: "none" },
    borderStyle: "double",
    borderColor: "#E2B84A",
    photoFrameStyle: "vintage",
    photoCornerRadius: 2,
    decorations: [
      { kind: "moon", anchor: "strip-top", size: 1.1, color: "#F0D080" },
      { kind: "leaf", anchor: "strip-bl", size: 0.85, color: "#C06030" },
      { kind: "sparkle", anchor: "strip-br", size: 0.75, color: "#E2B84A" },
    ],
    fontStyle: "classic",
    textColor: "#F0D8B0",
    filterPreset: "warm",
    filmGrain: true,
    customTextDefault: "cozy",
    preview: { swatch: "#2A1C18", accent: "#E2B84A" },
  },

  // —— Extra Holiday ——
  {
    id: "holiday-easter",
    name: "Easter Bloom",
    category: "Holiday",
    background: { color: "#F4FAF0", pattern: "dots", patternOpacity: 0.2 },
    borderStyle: "scalloped",
    borderColor: "#B0D080",
    photoFrameStyle: "rounded",
    photoCornerRadius: 14,
    decorations: [
      { kind: "flower", anchor: "strip-tl", size: 1, color: "#F0A0C8" },
      { kind: "butterfly", anchor: "strip-tr", size: 0.95, color: "#90C0E8" },
      { kind: "flower", anchor: "footer", size: 0.85, color: "#E8D060" },
    ],
    fontStyle: "handwritten",
    textColor: "#4A6A38",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "spring joy",
    preview: { swatch: "#F4FAF0", accent: "#B0D080" },
  },
  {
    id: "holiday-july4",
    name: "Sparklers",
    category: "Holiday",
    background: { color: "#F8F4F0", pattern: "stars", patternOpacity: 0.2, secondaryColor: "#D4213A" },
    borderStyle: "thick",
    borderColor: "#1A3A6A",
    photoFrameStyle: "thin",
    photoCornerRadius: 0,
    decorations: [
      { kind: "star", anchor: "strip-tl", size: 1, color: "#D4213A" },
      { kind: "star", anchor: "strip-tr", size: 0.9, color: "#1A3A6A" },
      { kind: "sparkle", anchor: "footer", size: 1, color: "#E2B84A" },
    ],
    fontStyle: "display",
    textColor: "#1A2A48",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "USA!",
    preview: { swatch: "#F8F4F0", accent: "#D4213A" },
  },
  {
    id: "holiday-spooky-cute",
    name: "Spooky Cute",
    category: "Holiday",
    background: { color: "#2A1830", pattern: "dots", patternOpacity: 0.2 },
    borderStyle: "scalloped",
    borderColor: "#C080FF",
    photoFrameStyle: "rounded",
    photoCornerRadius: 12,
    decorations: [
      { kind: "pumpkin", anchor: "strip-tl", size: 0.95 },
      { kind: "moon", anchor: "strip-tr", size: 0.9, color: "#F0E0A0" },
      { kind: "butterfly", anchor: "footer", size: 0.85, color: "#C080FF" },
    ],
    fontStyle: "handwritten",
    textColor: "#E8D0FF",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "cute scare",
    preview: { swatch: "#2A1830", accent: "#C080FF" },
  },

  // —— Indian festivals ——
  {
    id: "indian-diwali-night",
    name: "Diwali Night",
    category: "Indian",
    background: {
      color: "#1A1028",
      secondaryColor: "#FFB020",
      pattern: "stars",
      patternOpacity: 0.4,
    },
    borderStyle: "chrome",
    borderColor: "#E2B84A",
    photoFrameStyle: "rounded",
    photoCornerRadius: 8,
    decorations: [
      { kind: "diya", anchor: "strip-top", size: 1.15 },
      { kind: "sparkler", anchor: "strip-tl", size: 0.95, color: "#FFE8A0" },
      { kind: "sparkler", anchor: "strip-tr", size: 0.9, color: "#FFD060" },
      { kind: "star", anchor: "footer", size: 0.8, color: "#FFB020" },
    ],
    fontStyle: "display",
    textColor: "#FFE8A0",
    filterPreset: "warm",
    filmGrain: false,
    customTextDefault: "Happy Diwali",
    preview: { swatch: "#1A1028", accent: "#E2B84A" },
  },
  {
    id: "indian-cute-sparklers",
    name: "Cute Sparklers",
    category: "Indian",
    background: { color: "#FFF5F8", pattern: "stars", patternOpacity: 0.25, secondaryColor: "#FFB0C8" },
    borderStyle: "scalloped",
    borderColor: "#F2557A",
    photoFrameStyle: "rounded",
    photoCornerRadius: 14,
    decorations: [
      { kind: "sparkler", anchor: "strip-tl", size: 1.1, color: "#FF8AAD" },
      { kind: "sparkler", anchor: "strip-tr", size: 1, color: "#FFD060" },
      { kind: "heart", anchor: "between-photos", size: 0.75, color: "#F2557A" },
      { kind: "sparkle", anchor: "footer", size: 0.9, color: "#FFB020" },
    ],
    fontStyle: "handwritten",
    textColor: "#8A2848",
    filterPreset: "warm",
    filmGrain: false,
    customTextDefault: "sparkle season",
    preview: { swatch: "#FFF5F8", accent: "#F2557A" },
  },
  {
    id: "indian-golden-diyas",
    name: "Golden Diyas",
    category: "Indian",
    background: { color: "#2A1810", pattern: "glitter", patternOpacity: 0.35, secondaryColor: "#E2B84A" },
    borderStyle: "double",
    borderColor: "#E2B84A",
    photoFrameStyle: "vintage",
    photoCornerRadius: 2,
    decorations: [
      { kind: "diya", anchor: "strip-tl", size: 1 },
      { kind: "diya", anchor: "strip-tr", size: 0.95 },
      { kind: "marigold", anchor: "footer", size: 1, color: "#FF9A20" },
    ],
    fontStyle: "classic",
    textColor: "#FFE8A0",
    filterPreset: "warm",
    filmGrain: true,
    customTextDefault: "shubh diwali",
    preview: { swatch: "#2A1810", accent: "#E2B84A" },
  },
  {
    id: "indian-rangoli",
    name: "Rangoli Joy",
    category: "Indian",
    background: { color: "#FFF8F0", pattern: "dots", patternOpacity: 0.2 },
    borderStyle: "thick",
    borderColor: "#E04060",
    photoFrameStyle: "sticker",
    photoCornerRadius: 10,
    decorations: [
      { kind: "rangoli", anchor: "strip-top", size: 1.2 },
      { kind: "marigold", anchor: "strip-bl", size: 0.9, color: "#FF9A20" },
      { kind: "marigold", anchor: "strip-br", size: 0.85, color: "#FFB040" },
      { kind: "lotus", anchor: "footer", size: 0.9, color: "#F080A0" },
    ],
    fontStyle: "handwritten",
    textColor: "#8A2840",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "rangoli vibes",
    preview: { swatch: "#FFF8F0", accent: "#E04060" },
  },
  {
    id: "indian-holi",
    name: "Holi Splash",
    category: "Indian",
    background: { color: "#FFF0F8", pattern: "none" },
    borderStyle: "dashed",
    borderColor: "#C040E0",
    photoFrameStyle: "rounded",
    photoCornerRadius: 12,
    decorations: [
      { kind: "confetti", anchor: "strip-top", size: 1.15 },
      { kind: "flower", anchor: "strip-tl", size: 0.9, color: "#FF6AB0" },
      { kind: "flower", anchor: "strip-tr", size: 0.85, color: "#40C0FF" },
      { kind: "sparkle", anchor: "footer", size: 0.9, color: "#FFD040" },
    ],
    fontStyle: "display",
    textColor: "#6A2080",
    filterPreset: "none",
    filmGrain: false,
    customTextDefault: "Happy Holi!",
    preview: { swatch: "#FFF0F8", accent: "#C040E0" },
  },
  {
    id: "indian-lotus-night",
    name: "Lotus Lights",
    category: "Indian",
    background: {
      color: "#1C1430",
      secondaryColor: "#F0A0C8",
      pattern: "stars",
      patternOpacity: 0.35,
    },
    borderStyle: "scalloped",
    borderColor: "#E8A0C0",
    photoFrameStyle: "rounded",
    photoCornerRadius: 12,
    decorations: [
      { kind: "lotus", anchor: "strip-top", size: 1.15, color: "#F0A0C8" },
      { kind: "diya", anchor: "strip-bl", size: 0.85 },
      { kind: "sparkle", anchor: "strip-br", size: 0.85, color: "#FFE8A0" },
    ],
    fontStyle: "handwritten",
    textColor: "#F8D0E8",
    filterPreset: "warm",
    filmGrain: false,
    customTextDefault: "light within",
    preview: { swatch: "#1C1430", accent: "#F0A0C8" },
  },
  {
    id: "indian-sparkler-gold",
    name: "Gold Sparklers",
    category: "Indian",
    background: {
      color: "#201810",
      secondaryColor: "#FFD700",
      pattern: "glitter",
      patternOpacity: 0.45,
    },
    borderStyle: "chrome",
    borderColor: "#FFD700",
    photoFrameStyle: "thin",
    photoCornerRadius: 4,
    decorations: [
      { kind: "sparkler", anchor: "strip-tl", size: 1.15, color: "#FFE8A0" },
      { kind: "sparkler", anchor: "strip-tr", size: 1.1, color: "#FFD060" },
      { kind: "sparkler", anchor: "footer", size: 1, color: "#FFB020" },
      { kind: "star", anchor: "between-photos", size: 0.75, color: "#FFD700" },
    ],
    fontStyle: "display",
    textColor: "#FFE8A0",
    filterPreset: "warm",
    filmGrain: false,
    customTextDefault: "sparkle!",
    preview: { swatch: "#201810", accent: "#FFD700" },
  },
  {
    id: "indian-marigold-garland",
    name: "Marigold Garland",
    category: "Indian",
    background: { color: "#FFF6E8", pattern: "paper", patternOpacity: 0.2 },
    borderStyle: "thick",
    borderColor: "#E07020",
    photoFrameStyle: "polaroid",
    photoCornerRadius: 2,
    decorations: [
      { kind: "marigold", anchor: "strip-top", size: 1.15, color: "#FF9A20" },
      { kind: "marigold", anchor: "strip-bl", size: 0.9, color: "#FFB040" },
      { kind: "marigold", anchor: "strip-br", size: 0.85, color: "#E07020" },
      { kind: "diya", anchor: "footer", size: 0.85 },
    ],
    fontStyle: "handwritten",
    textColor: "#7A3A10",
    filterPreset: "warm",
    filmGrain: false,
    customTextDefault: "shaadi vibes",
    preview: { swatch: "#FFF6E8", accent: "#E07020" },
  },

  {
    id: "custom",
    name: "Custom Theme",
    category: "Custom",
    background: { color: "#FFFAF2", pattern: "none" },
    borderStyle: "thin",
    borderColor: "#1A1410",
    photoFrameStyle: "thin",
    photoCornerRadius: 0,
    decorations: [],
    fontStyle: "classic",
    textColor: "#1A1410",
    filterPreset: "none",
    filmGrain: false,
    preview: { swatch: "#FFFAF2", accent: "#C45C5C" },
  },
];

export function getTheme(id: string): StripTheme {
  return STRIP_THEMES.find((t) => t.id === id) ?? STRIP_THEMES[0];
}

export function themeToConfig(theme: StripTheme): StripThemeConfig {
  const base = createDefaultThemeConfig(theme.id);
  return {
    ...base,
    themeId: theme.id,
    background: { ...theme.background },
    borderStyle: theme.borderStyle,
    borderColor: theme.borderColor,
    photoFrameStyle: theme.photoFrameStyle,
    photoCornerRadius: theme.photoCornerRadius,
    decorations: decorationsFromPreset(theme.decorations),
    fontStyle: theme.fontStyle,
    textColor: theme.textColor,
    filterPreset: theme.filterPreset,
    filmGrain: theme.filmGrain,
    customText: theme.customTextDefault ?? "",
    dateStamp: true,
  };
}

export function themesByCategory(category: string): StripTheme[] {
  return STRIP_THEMES.filter((t) => t.category === category);
}
